export const inventory = [
    {
        item: "Computer",
        quantity: 1,
        price: 1000,
        in_stock: true,
        type: ["electronic"],
    },
    {
        item: "Phone",
        quantity: 1,
        price: 800,
        in_stock: false,
        type: ["electronic"],
    },
    {
        item: "Tablet",
        quantity: 1,
        price: 900,
        in_stock: true,
        type: ["electronic"],
    },
    {
        item: "Headphones",
        quantity: 1,
        price: 300,
        in_stock: true,
        type: ["electronic"],
    },
    {
        item: "Earbuds",
        quantity: 1,
        price: 18,
        in_stock: true,
        type: ["electronic"],
    },
    {
        item: "Pencils",
        quantity: 10,
        price: 5,
        in_stock: true,
        type: ["craft", "school"],
    },
    {
        item: "Markers",
        quantity: 8,
        price: 6,
        in_stock: true,
        type: ["school", "craft"],
    },
    {
        item: "Folders",
        quantity: 2,
        price: 4,
        in_stock: true,
        type: ["school"],
    },
    {
        item: "Binder",
        quantity: 1,
        price: 5,
        in_stock: false,
        type: ["school"],
    },
    {
        item: "Calculator",
        quantity: 1,
        price: 100,
        in_stock: false,
        type: ["school", "electronics"],
    },
    {
        item: "Notebook",
        quantity: 1,
        price: 5,
        in_stock: true,
        type: ["school"],
    },
]
